sudo: false
dist: trusty
language: python

services:
  - rabbitmq

install:
  - pip install tox

matrix:
  include:
    - stage: static
      python: 2.7
      env: TOX_ENV=py27-static
    - stage: static
      python: 3.6
      env: TOX_ENV=py36-static
    - stage: test
      python: 2.7
      env: TOX_ENV=py27-test
    - stage: test
      python: 3.4
      env: TOX_ENV=py34-test
    - stage: test
      python: 3.5
      env: TOX_ENV=py35-test
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: mattbennett
        password:
          secure: "E68NUiQ72jbJ6BVZWp9gsASjESwjuvWiHTprkJxI+y/1lnGBrEt4TROioUZFzSdi17sM072TJy/fiVaWtgXfWWbwWqTFGCzT57wcCFjFAw68+dM3LRL1LitHm0+PyyN47IhtbPLUrtWUc/JHV9O9bqGdHmBIQqVGbeanglMZ0p97HkCLwSQYU46hUsM2MQ1uXyPh2gKI0vhnSXIsuuYuw+61YQFmZ5WQbgEewuBlYwip1CCkiwClbspfQRWriVgbiyp4KbSbeCITPDX5OZBw1x5tB8o7aZMMKnxhP+OybFbw7PsfNIiW6YGusKldiJoLO3QCaPfbv4PE2zp1oivFjkAlbAfFjcsdFH/gnbDZK01o4RB65TB53Mg94lTq05rFH5cK5BMMuouIdnHQCDRMmY8SzGV8KmXprAhq8UGwI4HJIw0q5vWrNOoxedcBF+gaI0YMT1l70lSW+ioypF99JhdU78lWzHOGnjQsKkWriSznazNBLVvZ6mvozXtr/stHZYpiotSB1X04Cps/XXB4AVsqQjFk22uiOb8nv1jWHZxziuX28VEoebJA4K6OP8pxZnQ9/esGTx6Yqfzl4H/DxsA/qDaJa0pS9R3aT6TQ4aaKL7YPWdFJvJF8vSSijYmfW1boRlvUnuagjW+Zsv4LqKjwzbZHCfAbOR09IqeI6+E="  
        on:
          tags: true
          repo: nameko/nameko-sentry

script:
  - tox -e $TOX_ENV
